create schema if not exists CD;

CREATE TABLE CD.cd_password (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	password_hash varchar(100)
);

CREATE TABLE CD.cd_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    role_type varchar(255)
);

CREATE TABLE CD.cd_person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    password_id BIGINT
);

CREATE TABLE CD.cd_person_role (
    person_id BIGINT,
    role_id BIGINT
);
