create schema if not exists JPA;

CREATE TABLE JPA.Employee_enum (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	salary_rate varchar(255) not null,
	status INT
);

insert into JPA.Employee_enum (salary_rate, status) values ('MANAGER', 1);